#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#
#                                                               #
#       _____      _   _     ______ _           _               #
#      |  __ \    | | | |   |  ____(_)         | |              #
#      | |__) |_ _| |_| |__ | |__   _ _ __   __| | ___ _ __     #
#      |  ___/ _` | __| '_ \|  __| | | '_ \ / _` |/ _ \ '__|    #
#      | |  | (_| | |_| | | | |    | | | | | (_| |  __/ |       #
#      |_|   \__,_|\__|_| |_|_|    |_|_| |_|\__,_|\___|_|       #
#                        Configuration                          #
#                                                               #
#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#=#